set(CMAKE_SYSTEM_NAME Generic)
set(CMAKE_SYSTEM_PROCESSOR riscv)
set(CMAKE_TRY_COMPILE_TARGET_TYPE STATIC_LIBRARY)
if(NOT WK_SDK_PATH)
  set(WK_SDK_PATH "$ENV{WK_SDK_PATH}")
endif()
if(NOT WK_SDK_PATH)
  message(FATAL_ERROR "Set WK_SDK_PATH to the Welrok SDK directory")
endif()
set(WK_SDK_PATH "${WK_SDK_PATH}" CACHE PATH "Welrok SDK")
set(CMAKE_TRY_COMPILE_PLATFORM_VARIABLES WK_SDK_PATH)
set(_bin "${WK_SDK_PATH}/WCH/RISCV_GCC12/bin")
set(CMAKE_C_COMPILER "${_bin}/riscv-none-elf-gcc.exe")
set(CMAKE_ASM_COMPILER "${CMAKE_C_COMPILER}")
set(CMAKE_OBJCOPY "${_bin}/riscv-none-elf-objcopy.exe")
set(CMAKE_SIZE "${_bin}/riscv-none-elf-size.exe")
